// <auto-generated />
using System;
using CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221004022447_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Entities.ChangeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChangeType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User created"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User Updated"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User Deleted"
                        });
                });

            modelBuilder.Entity("CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "GBR",
                            Name = "United Kingdom",
                            Value = 44
                        },
                        new
                        {
                            Id = 2,
                            Code = "USA",
                            Name = "United States of America",
                            Value = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "CRI",
                            Name = "Costa Rica",
                            Value = 506
                        },
                        new
                        {
                            Id = 3,
                            Code = "ARG",
                            Name = "Argentina",
                            Value = 54
                        });
                });

            modelBuilder.Entity("CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Entities.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ChangeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<int?>("ChangeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CurrValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrevValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_History");

                    b.HasIndex("ChangeTypeId");

                    b.HasIndex(new[] { "UserId" }, "IX_History_User");

                    b.ToTable("History", (string)null);
                });

            modelBuilder.Entity("CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Telephone")
                        .HasColumnType("int");

                    b.Property<bool>("WishesToBeContacted")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.HasIndex("CountryId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Entities.History", b =>
                {
                    b.HasOne("CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Entities.ChangeType", null)
                        .WithMany("Histories")
                        .HasForeignKey("ChangeTypeId");

                    b.HasOne("CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("ChangeHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_History_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.HasOne("CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Entities.Country", null)
                        .WithMany("Users")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Entities.ChangeType", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Entities.Country", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CEZ.LoymarkTechTest.WebAPI.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Navigation("ChangeHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
